[package]
name = "multiaddr"
description = "Implementation of the multiaddr format"
homepage = "https://github.com/Dignifiedquire/rust-multiaddr"

keywords = ["multiaddr", "ipfs"]

version = "0.1.0"

authors = ["dignifiedquire <dignifiedquire@gmail.com>"]

license = "MIT"

readme = "README.md"

[dependencies]
byteorder = "~0.4"
nom = {git = "https://github.com/Geal/nom.git"}
